context:
  name: check-dist
  version: "0.1.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/check_dist/check_dist-${{ version }}.tar.gz
  sha256: cfca372a6f4d623ed82ebe67b51068d015d8fd3e969fafc74e1da580fdd45768

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - pyyaml
    - tomli

tests:
  - python:
      imports:
        - check_dist
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Check Python source and wheel distributions
  homepage: https://github.com/python-project-templates/check-dist
  repository: https://github.com/python-project-templates/check-dist

extra:
  recipe-maintainers:
    - timkpaine
